### ISSUE TITLE
Caps Lock mask is still QWERTY

### ISSUE THREAD

**Issue by brandonforster** [chid/dvorak-qwerty#1]
This is kind of hard to explain, but

`'`, `,` and `.` keys in Dvorak get caps in caps lock mode, because in QWERTY that's `Q``W``E` but `V``Z` doesn't get caps because that would be `.``/`

**Comment by chid** [comment]
Thanks for opening up an issue. I did not write this but just put this as a place to store the files which have now being lost to the vicious internet cycle.

Shortly after originally committing this repo this I came across dvorak-querty in Autohotkey which works quite nicely https://autohotkey.com/board/topic/25093-mac-style-dvorak-qwerty-command-layout-switcher-for-windows/

Let me know if this fits what you're after.

**Comment by brandonforster** [comment]
Gotcha. No, that would probably be worse for my usecase since that is literally translating keys. This program does something funky with the positions of keys or something, because with zero configuration games like WoW think my keyboard is QWERTY for keybinds while letting me type in Dvorak. That's probably also a bug, but a SUPER HELPFUL one, helpful enough where I'm willing to give up caps lock.

I really appreciate you having this repo open, because yes, all those links are dead. Thanks again :)
